name: CI

on:
  push:
    branches: [ main, dev, basic-auth ]
  pull_request:
    branches: [ main, dev, basic-auth ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests
      run: mvn test
    - name: Run application for database initialization
      run: |
        mvn spring-boot:run &
        PID=$!
        sleep 30
        kill $PID
